### ISSUE TITLE
Infinite loop when crt or key file isn't readable by the browser

### ISSUE THREAD

**Issue by sbadia** [jvaubourg/vpnclient_ynh#3]
Tested with iceweasel on debian jessie (`31.3.0esr-1`), when I upload a `client.key` not readable be me (the current user) vpnclient doesn't show an error message (input validation) but this lead to an infinite loop.

**Comment by jvaubourg** [comment]
There is no infinite loop in this case, because actually, Firefox does not really submit the form. The page is not loading and there is just a GIF close to the button giving this impression. The browser should fail with a message and not silently, but this is [an opened bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=426177). I'd not found a way to work around this problem because nothing indicates to javascript that the submit failed. The only one solution is to send data through AJAX, with a file uploader (a jquery plugin) for the certificates. This implies many changes and risks of incompatibility, just for working around this bug of Firefox. Instead, [I just add a Tooltip](https://github.com/jvaubourg/vpnclient_ynh/commit/0d1675eeab1646ef392232af7e72bf0e477ee6c4) on the file browsing button for asking to check if the browser is able to read the key file. Please, reopen this bug if someone has a better solution.
